# Generated by Django 5.1.5 on 2025-03-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractdetails',
            name='notice_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
