# Generated by Django 5.1.5 on 2025-03-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_alter_contractdetails_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractproposal',
            name='pdf_path',
        ),
        migrations.AddField(
            model_name='contractproposal',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='contracts/'),
        ),
    ]
