# Generated by Django 5.1.5 on 2025-03-16 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_companydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_plan',
        ),
    ]
